kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: nordmart-dev-keycloak
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: keycloak
    expose: "true"
    helm.sh/chart: keycloak-5.1.7
  name: keycloak-dev
spec:
  host: keycloak-stakater-nordmart-test.stakater-200205-1-5c84fa685b23fe4798253ee758d532d0-0000.eu-de.containers.appdomain.cloud
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nordmart-dev-keycloa-http
    weight: 100
  wildcardPolicy: None
