rbac:
  create: false
serviceAccount:
  create: false
  name: flux
image:
  repository: weaveworks/flux
  tag: 1.10.1
helmOperator:
  create: false
git:
  url: ssh://git@github.com/stakater-lab/nordmart-dev-apps.git
  pollInterval: "10s"
  path: "releases"
registry:
  pollInterval: "1m"
  excludeImage: "None"
additionalArgs:
  - --k8s-namespace-whitelist=nordmart-dev-apps
